export const SET_VEHICLE_TYPE = 'SET_VEHICLE_TYPE'
export const STORE_COMBINED_CARPARK_DATA = 'STORE_COMBINED_CARPARK_DATA'
export const STORE_COMBINED_CARPARK_DATA_ERROR = 'STORE_COMBINED_CARPARK_DATA'
export const SET_DARK_MODE = 'SET_DARK_MODE'